image:
  registry: docker.io
  repository: bitnami/wordpress
  tag: 6.8.1-debian-12-r1

wordpressUsername: admin
wordpressPassword: ""

wordpressEmail: admin@ysys.hu
wordpressFirstName: Aladar
wordpressLastName: Szia
wordpressBlogName: User's Blog!

wordpressSkipInstall: false

persistence:
  enabled: true
  size: 5Gi

mariadb:
  enabled: true
