name: "FAST bootstrap stage"

on:
  push:
    branches:
      - main
      - test
jobs:
  pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v4

      - id: gcp-auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/678357795040/locations/global/workloadIdentityPools/github-pool/providers/github-provider 
          access_token_lifetime: 900s
          project_id: intern-461913

      - id: gcp-sdk
        name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - id: compute-list 
        name: GCP compute list 
        run: |
          gcloud compute list
